apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: minio
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-secret
    creationPolicy: Owner
  data:
    - secretKey: root-user
      remoteRef:
        key: secret/minio
        property: root-user
    - secretKey: root-password
      remoteRef:
        key: secret/minio
        property: root-password
