apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-backup
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-backup
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vault-keys"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    resourceNames: ["vault-0"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-backup
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault-backup
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-backup-minio
subjects:
  - kind: ServiceAccount
    name: vault-backup
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-backup-minio
  namespace: minio
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["minio-secret"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-backup-minio
  namespace: minio
subjects:
  - kind: ServiceAccount
    name: vault-backup
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-backup-minio
